## Meet Your Faculty

Coming soon!

## AWS setup instructions

### Course data downloads
Note that some of these files are quite large. If you have issues downloading them, try copying the link address, opening a new blank tab, and entering the URL into the new tab’s address bar. If that fails, contact us at info@bioinformatics.ca.

https://hpc4health.ca/cbw/2025/ISO-v/scripts_coursedata.zip  
https://hpc4health.ca/cbw/2025/ISO-v/data/ffpe_mouse_10x.tar  
https://hpc4health.ca/cbw/2025/ISO-v/data/frozen_mouse_10x.tar  
https://hpc4health.ca/cbw/2025/ISO-v/data/xenium_mouse_10x.tar  
https://hpc4health.ca/cbw/2025/ISO-v/data/subclass_celltype_label.csv  

### Amazon Machine Image

We have made our AWS AMI (Amazon Machine Image) publicly available. To launch your own instance, follow the [instructions provided by Amazon on how to launch an EC2 instance from a custom Amazon Machine Image](https://repost.aws/knowledge-center/launch-instance-custom-ami). Please note that you will need an AWS account to proceed, and that you will need to upload the CourseData files yourself.

Here are the details of the AMI:

AWS Region: us-east-1 (N. Virginia)  
AMI type: public image  
AMI name: CBW_ISO_250218  
AMI ID: ami-02bccaa393b482b4d  

If you want to create and activate a new AWS account, please follow [these instructions provided by Amazon](https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/).
